package com.company.ops_hub_api.service;

public enum AiIntent {
    GENERAL_SUMMARY,
    PENDING_PAYMENTS_SUMMARY,
    PAYMENTS_SUMMARY,
    CUSTOMER_STATUS_SUMMARY,
    ALLOCATION_SUMMARY,
    AGENT_PERFORMANCE,
    VISIT_SUMMARY,
    NOTIFICATIONS_SUMMARY,
    UPLOADS_SUMMARY,
    UNKNOWN
}
